# conda env create -f environment.yml && conda activate chin_ups
#
name: chin_ups
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ffmpeg
  - py-opencv
  - numpy
  - matplotlib-base
  - pillow
  - rich
  - python-dotenv
  - pip
  - pip:
      - openai>=1.40
